// users
export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const USER_LOCATION_SET = "USER_LOCATION_SET";
export const USER_USERNAME_SET = "USER_USERNAME_SET";
export const USER_KEY_FETCHED = "USER_KEY_FETCHED";
export const USER_ACTIVITY_FETCHED = "USER_ACTIVITY_FETCHED";
export const CLEAR_ACTIVITY = "CLEAR_ACTIVITY";
export const ANALYTICS_FETCHED = "ANALYTICS_FETCHED";
export const DETAILS_CHECKED = "DETAILS_CHECKED";

// locations
export const LOCATION_COUNTRIES_FETCHED = "LOCATION_COUNTRIES_FETCHED";
export const LOCATION_STATES_FETCHED = "LOCATION_STATES_FETCHED";
export const LOCATION_CITIES_FETCHED = "LOCATION_CITIES_FETCHED";
export const CLEAR_CITIES = "CLEAR_CITIES";

// images
export const IMAGE_UPLOADED = "IMAGE_UPLOADED";
export const IMAGE_FETCHED = "IMAGE_FETCHED";

// posts
export const POST_UPLOADED = "POST_UPLOADED";
export const POSTS_FETCHED = "POSTS_FETCHED";
export const POST_FETCHED = "POST_FETCHED";
export const POSTS_CLEARED = "POSTS_CLEARED";
export const POST_FETCHED_BY_ID = "POST_FETCHED_BY_ID";
export const POST_DELETED = "POST_DELETED";

// others
export const CATEGORY_OPTIONS_FETCHED = "CATEGORY_OPTIONS_FETCHED";
export const CATEGORY_ADDED = "CATEGORY_ADDED";
export const CATEGORY_UPDATED = "CATEGORY_UPDATED";
export const CATEGORY_DELETED = "CATEGORY_DELETED";
export const TOP_EIGHT_HASHTAGS_FETCHED = "TOP_EIGHT_HASHTAGS_FETCHED";
export const HASHTAGS_FETCHED = "HASHTAGS_FETCHED";
export const HASHTAGS_CLEARED = "HASHTAGS_CLEARED";

// adposts other
export const ADPOST_PER_CHANGED = "ADPOST_PER_CHANGED";
export const ADPOST_PAGE_CHANGED = "ADPOST_PAGE_CHANGED";
export const ADPOST_TOTALPAGES_CHANGED = "ADPOST_TOTALPAGES_CHANGED";

// path for redirecting user when comes with link and if he has not having any session
// then path is stored and make user make one session or login session and redirect him to the route 
// he asked for.
export const PATH_ADDED = "PATH_ADDED";

//  admins
export const ADMIN_LOGGED_IN = "ADMIN_LOGGED_IN";
export const ADMIN_LOGGED_OUT = "ADMIN_LOGGED_OUT";
export const PASSWORD_CHANGED = "PASSWORD_CHANGED";

// admin posts
export const ADPOST_UPLOADED = "ADPOST_UPLOADED";
export const ADPOSTS_FETCHED = "ADPOSTS_FETCHED";
export const ADPOST_FETCHED = "ADPOST_FETCHED";
export const ADPOSTS_CLEARED = "ADPOSTS_CLEARED";
export const ADPOST_FETCHED_BY_ID = "ADPOST_FETCHED_BY_ID";
export const ADPOST_DELETED = "ADPOST_DELETED";

// admin Statistics
export const TOTAL_ACCOUNTS_FETCHED = "TOTAL_ACCOUNTS_FETCHED";
export const NO_ACCOUNTS_FETCHED = "NO_ACCOUNTS_FETCHED";
export const COUNTRY_STATS_FETCHED = "COUNTRY_STATS_FETCHED";
export const STATS_BY_COUNTRY_CLEARED = "STATS_BY_COUNTRY_CLEARED";
export const STATE_STATS_FETCHED = "STATE_STATS_FETCHED";
export const STATS_BY_STATE_CLEARED = "STATS_BY_STATE_CLEARED";